<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ICSharpCode.CodeConverter.VsCodeExtension.Worker</AssemblyName>
    <RootNamespace>ICSharpCode.CodeConverter.VsCodeExtension.Worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeConverter\CodeConverter.csproj" />
  </ItemGroup>
</Project>
